version: "2.0"
services:
  solgram:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    image: soluna-gram:local
    restart: always
    container_name: solgram
    hostname: solgram
    volumes:
      - ./data:/solgram/workdir/data
